image: maven:3.9.6-eclipse-temurin-17

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SELENIUM_GRID_URL: "http://selenium-hub:4444/wd/hub"

cache:
  paths:
    - .m2/repository

run-tests:
  stage: test
  services:
    - name: selenium/hub:4.18.1
      alias: selenium-hub
    - name: selenium/node-chrome:4.18.1
      alias: chrome-node
      variables:
        SE_EVENT_BUS_HOST: selenium-hub
        SE_EVENT_BUS_PUBLISH_PORT: "4442"
        SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
    - name: selenium/node-firefox:4.18.1
      alias: firefox-node
      variables:
        SE_EVENT_BUS_HOST: selenium-hub
        SE_EVENT_BUS_PUBLISH_PORT: "4442"
        SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
  script:
    - mvn verify -Dgrid.url=$SELENIUM_GRID_URL -Dbrowser=chrome
  artifacts:
    when: always
    paths:
      - target/cucumber-html-reports/
    expire_in: 7 days
